#!/usr/bin/env python3
"""Regenerate curves_data.js for the interactive sample-efficiency figure
(fig_curves_embed.html), INCLUDING the wandb learning curves.

Run this ON TARS next to the paper plotting script (it imports plot_main.py
for the task data, colors, and the exact resample/smooth processing):

    cd ~/icml2026_plots && python3 make_curves.py curves_data.js

then copy the output to the website's static/figs/explore_viz/curves_data.js.
The inline data (expert / Ours / offline baselines) matches what plot_main.py
hardcodes; BC+PPO and ADVISOR curves are fetched from wandb and processed with
plot_main's resample_log_space + smooth_curve, so the interactive figure shows
the same curves as the paper's final_comparison2.png.
"""
import json, math, sys

import numpy as np
import plot_main as pm

DISPLAY = {"Tactile-Cube-Pick": "Tactile Cube Pick",
           "Wrist-Peg-Insertion": "Wrist Peg Insertion"}


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "curves_data.js"
    data = {
        "order": ["Ours", "BC", "AAWR", "SPOC", "DPT", "BC+PPO", "ADVISOR"],
        "colors": {k: v for k, v in pm.METHOD_COLORS.items()},
        "markers": {"Ours": "circle", "DPT": "square", "SPOC": "triangle-up",
                    "BC+PPO": "triangle-down", "AAWR": "triangle-right",
                    "ADVISOR": "pentagon", "BC": "hexagon"},
        "labels": {"Ours": "ASTEROID (ours)"},
        "tasks": [],
    }
    for task in pm.TASK_NAMES:
        td, params = pm.TASK_DATA[task], pm.TASK_PARAMS[task]
        n_seeds = params["n_seeds"]
        entry = {"name": DISPLAY.get(task, task), "expert": td["expert"][0],
                 "xlim": [99900, 1e8], "ylim": list(params["ylim"]), "methods": {}}
        for m, md in td.items():
            if m == "expert":
                continue
            if m == "Ours":
                means, stds, steps = pm.process_ours_data(md)
                entry["methods"][m] = {"type": "iters", "x": steps.tolist(),
                                       "mean": np.round(means, 4).tolist(),
                                       "stderr": np.round(stds / math.sqrt(n_seeds), 4).tolist()}
            elif isinstance(md, list):
                means, stds, steps = pm.process_rl_data(md, params["metric"],
                                                        params["steps_per_update"], n_seeds)
                if means is None:
                    continue
                stderr = stds / math.sqrt(n_seeds)
                x, mean = pm.resample_log_space(steps, means)
                _, se = pm.resample_log_space(steps, stderr)
                mean, se = pm.smooth_curve(mean), pm.smooth_curve(se)
                entry["methods"][m] = {"type": "curve", "x": np.round(x, 1).tolist(),
                                       "mean": np.round(mean, 4).tolist(),
                                       "stderr": np.round(se, 4).tolist()}
            else:
                mean, std, _ = md
                entry["methods"][m] = {"type": "flat", "mean": round(mean, 4),
                                       "stderr": round(std / math.sqrt(n_seeds), 4)}
        data["tasks"].append(entry)
    with open(out_path, "w") as f:
        f.write("// generated by make_curves.py from plot_main.py (+ wandb learning curves)\n"
                "window.CURVES_DATA = " + json.dumps(data, separators=(",", ":")) + ";\n")
    print("wrote", out_path)


if __name__ == "__main__":
    main()
